/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        background:                "#080808",
        surface:                   "#080808",
        "surface-dim":               "#080808",
        "surface-bright":            "#222222",
        "surface-container-lowest":  "#000000",
        "surface-container-low":     "#111111",
        "surface-container":         "#141414",
        "surface-container-high":    "#181818",
        "surface-container-highest": "#1c1c1c",
        "surface-variant":           "#212121",
        outline:                   "#333333",
        "outline-variant":           "#262626",
        "on-surface":                "#ffffff",
        "on-surface-variant":        "#888888",
        "on-background":             "#ffffff",
        "inverse-surface":           "#fcf9f8",
        "inverse-on-surface":        "#565555",
        primary:                   "#ff915a",
        "primary-container":         "#ff7a31",
        "primary-fixed":             "#ff7a31",
        "primary-fixed-dim":         "#f76600",
        "primary-dim":               "#ff7526",
        "on-primary":                "#531e00",
        "on-primary-container":      "#411500",
        "on-primary-fixed":          "#000000",
        "on-primary-fixed-variant":  "#501c00",
        "inverse-primary":           "#a24100",
        "surface-tint":              "#ff915a",
        secondary:                 "#ff923c",
        "secondary-container":       "#954a00",
        "secondary-fixed":           "#ffc6a0",
        "secondary-fixed-dim":       "#ffb37e",
        "secondary-dim":             "#ee8530",
        "on-secondary":              "#4d2300",
        "on-secondary-container":    "#fff6f2",
        "on-secondary-fixed":        "#552800",
        "on-secondary-fixed-variant":"#803f00",
        tertiary:                  "#ffc96f",
        "tertiary-container":        "#ffb627",
        "tertiary-fixed":            "#ffb627",
        "tertiary-fixed-dim":        "#efa914",
        "tertiary-dim":              "#efa914",
        "on-tertiary":               "#614100",
        "on-tertiary-container":     "#553900",
        "on-tertiary-fixed":         "#3a2600",
        "on-tertiary-fixed-variant": "#604100",
        error:                     "#ff7351",
        "error-dim":                 "#d53d18",
        "error-container":           "#b92902",
        "on-error":                  "#450900",
        "on-error-container":        "#ffd2c8",
        border: "var(--color-border)",
        input: "var(--color-input)",
        ring: "var(--color-ring)",
      },
      borderRadius: {
        DEFAULT: "0.375rem",
        lg:      "0.75rem",
        xl:      "1rem",
        "2xl":   "1.5rem",
        "3xl":   "2rem",
        full:    "9999px",
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body:     ['"Inter"', 'sans-serif'],
        label:    ['"Inter"', 'sans-serif'],
        sans:     ['"Inter"', 'sans-serif'],
        mono:     ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
      },
      animation: {
        "fade-in": "fadeIn 200ms cubic-bezier(0.4, 0, 0.2, 1)",
        "slide-up": "slideUp 300ms cubic-bezier(0.4, 0, 0.2, 1)",
        "pulse-gentle": "pulseGentle 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        pulseGentle: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.8" },
        },
      },
      boxShadow: {
        'soft': '0 1px 3px rgba(0, 0, 0, 0.1)',
        'elevated': '0 4px 12px rgba(0, 0, 0, 0.15)',
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
  ],
}