/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        background:                "#080808",
        surface:                   "#080808",
        "surface-dim":               "#080808",
        "surface-bright":            "#222222",
        "surface-container-lowest":  "#000000",
        "surface-container-low":     "#111111",
        "surface-container":         "#141414",
        "surface-container-high":    "#181818",
        "surface-container-highest": "#1c1c1c",
        "surface-variant":           "#212121",
        outline:                   "#333333",
        "outline-variant":           "#262626",
        "on-surface":                "#ffffff",
        "on-surface-variant":        "#888888",
        "on-background":             "#ffffff",
        "inverse-surface":           "#fcf9f8",
        "inverse-on-surface":        "#565555",
        primary:                   "#6366f1", // Indigo
        "primary-container":         "#4f46e5",
        "primary-fixed":             "#818cf8",
        "primary-fixed-dim":         "#6366f1",
        "primary-dim":               "#4f46e5",
        "on-primary":                "#ffffff",
        "on-primary-container":      "#e0e7ff",
        "on-primary-fixed":          "#000000",
        "on-primary-fixed-variant":  "#312e81",
        "inverse-primary":           "#818cf8",
        "surface-tint":              "#6366f1",
        secondary:                 "#06b6d4", // Cyan
        "secondary-container":       "#0891b2",
        "secondary-fixed":           "#22d3ee",
        "secondary-fixed-dim":       "#06b6d4",
        "secondary-dim":             "#0891b2",
        "on-secondary":              "#000000",
        "on-secondary-container":    "#cffafe",
        "on-secondary-fixed":        "#000000",
        "on-secondary-fixed-variant":"#164e63",
        tertiary:                  "#a855f7", // Purple
        "tertiary-container":        "#9333ea",
        "tertiary-fixed":            "#c084fc",
        "tertiary-fixed-dim":        "#a855f7",
        "tertiary-dim":              "#9333ea",
        "on-tertiary":               "#ffffff",
        "on-tertiary-container":     "#f3e8ff",
        "on-tertiary-fixed":         "#000000",
        "on-tertiary-fixed-variant": "#581c87",
        error:                     "#f43f5e",
        "error-dim":                 "#e11d48",
        "error-container":           "#9f1239",
        "on-error":                  "#ffffff",
        "on-error-container":        "#ffe4e6",
        border: "var(--color-border)",
        input: "var(--color-input)",
        ring: "var(--color-ring)",
      },
      borderRadius: {
        DEFAULT: "0.375rem",
        lg:      "0.75rem",
        xl:      "1rem",
        "2xl":   "1.5rem",
        "3xl":   "2rem",
        full:    "9999px",
      },
      fontFamily: {
        headline: ['"Poppins"', 'sans-serif'],
        body:     ['"Poppins"', 'sans-serif'],
        label:    ['"Poppins"', 'sans-serif'],
        sans:     ['"Poppins"', 'sans-serif'],
        mono:     ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
      },
      animation: {
        "fade-in": "fadeIn 200ms cubic-bezier(0.4, 0, 0.2, 1)",
        "slide-up": "slideUp 300ms cubic-bezier(0.4, 0, 0.2, 1)",
        "pulse-gentle": "pulseGentle 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        pulseGentle: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.8" },
        },
      },
      boxShadow: {
        'soft': '0 1px 3px rgba(0, 0, 0, 0.1)',
        'elevated': '0 4px 12px rgba(0, 0, 0, 0.15)',
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
  ],
}