
services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:root@db:5432/interview_db"
      OLLAMA_BASE_URL: "http://ollama:11434"
    depends_on:
      - ollama


volumes:
  ollama_data: