version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: interview_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  ollama:
    image: ollama/ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: >
      sh -c "
        ollama serve &
        sleep 5 &&
        ollama pull all-minilm:l6-v2 &&
        wait
      "

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:root@db:5432/interview_db"
      OLLAMA_BASE_URL: "http://ollama:11434"
    depends_on:
      - db
      - ollama
    volumes:
      - whisper_cache:/root/.cache/huggingface
      - kokoro_cache:/root/.cache/kokoro

volumes:
  postgres_data:
  ollama_data:
  whisper_cache:
  kokoro_cache: